### ISSUE TITLE
Toyhouse thinks it's a bot

### ISSUE THREAD

**Issue by fishainsley** [Provinite/toyhouse-downloader#3]
while that is true, that is also causing it to not work.
![login-failed](https://github.com/Provinite/toyhouse-downloader/assets/172628614/13a9681e-d609-4500-9ed5-bb463b61a815)

I have tried both with and without my VPN running and gotten the same results.
Log from 3rd or so time i ran it:

 [ThD][11:44:33] info  : Installing chromium to C:\Users\ainsl\OneDrive\Desktop\toyhouse backup\thdownloader-windows-x64\chromium
 [ThD][11:44:38] info  : Starting chromium from C:\Users\ainsl\OneDrive\Desktop\toyhouse backup\thdownloader-windows-x64\chromium\chrome-win\chrome.exe
 [ThD][11:44:39] info  : [Login]
 [ThD][11:44:40] debug : Navigated to https://toyhou.se/
 [ThD][11:44:41] info  : Not logged in. Logging in as fishainsley
 [ThD][11:44:41] debug : Navigated to https://toyhou.se/~account/login
 [ThD][11:44:48] debug : Navigated to https://toyhou.se/~account/login
 [ThD][11:44:49] info  : Saving screenshot of https://toyhou.se/~account/login to ./login-failed.jpg
 [ThD][11:44:50] error : Fatal error during downloading process
 [ThD][11:44:50] error : undefined
 [ThD][11:44:50] error : Error: Error logging in. Please check your username and password. See login-failed.jpg for a screenshot of what happened.
    at loginToToyhouse (C:\snapshot\toyhouse-downloader\build\toyhouse.puppeteer.js:34:19)
    at async main (C:\snapshot\toyhouse-downloader\build\app.js:40:9)
 [ThD][11:44:50] info  : Shutting down

**Comment by fishainsley** [comment]
Fixed with latest update

**Comment by Provinite** [comment]
Glad this is resolved, please reach out if you run into further issues _o/
